name: Preview

on:
  push:
    branches:
      - main
    paths:
      - resume.tex
      - resume.cls
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Generate PDF
      uses: xu-cheng/latex-action@master
      with:
        root_file: |
          resume.tex
        args: |
          -pdf -interaction=nonstopmode -halt-on-error -jobname=Preview

    - name: Upload preview artifacts
      uses: actions/upload-artifact@v1
      with:
        name: resume-preview
        path: Preview.pdf
