name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Generate PDF
        uses: xu-cheng/latex-action@master
        with:
          root_file: |
            resume.tex
          args: |
            -pdf -interaction=nonstopmode -halt-on-error -jobname=Preview

      - name: Upload preview artifacts
        uses: actions/upload-artifact@v1
        with:
          name: resume-preview
          path: Preview.pdf

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Preview.pdf
          draft: false
          prerelease: false
